### ISSUE TITLE
Where is requirements.txt?

### ISSUE THREAD

**Issue by anews9342** [WeOpenML/PandaLM#1]
PandaLM$ ls
README.md  data  figures  pandalm
PandaLM/pandalm$ ls
__init__.py  assets  core  inst-tune.py  run-gradio.py  scripts  utils

**Comment by qianlanwyd** [comment]
We will upload it recently.

**Comment by zhuohaoyu** [comment]
requirement.txt and conda-env.yml added, please use your preferred way to reproduce our environment.
