### ISSUE TITLE
请问有pandaLM模型本身的训练微调代码么

### ISSUE THREAD

**Issue by pandaDevs** [WeOpenML/PandaLM#14]
目前pandaLM评价的是LLM模型结果对比，如果是非语言的其他类型任务大模型，可能需要微调来进行训练。请问有pandaLM模型本身的训练微调代码么

**Comment by uestcljx** [comment]
同问，目前开源的是candidate LLM的训练微调代码，后续是否会开源pandaLM模型本身的训练微调代码呢？

**Comment by qianlanwyd** [comment]
Data uploaded. PandaLM can be easily trained use our codes and data.
