### ISSUE TITLE
Questions about experimental results and training data

### ISSUE THREAD

**Issue by uestcljx** [WeOpenML/PandaLM#19]
I have read your paper and it is very well written. However, I have two questions to ask:

1. The results in Table 3 are impressive. After PandaLM parameter adjustment, the language model has a higher probability of outputting answers that humans prefer. I would like to know which type(s) of the problems are that the model can output answers that humans prefer after PandaLM tuning parameters, and which ones are not? Have you done any analysis on this?

![20230613145029](https://github.com/WeOpenML/PandaLM/assets/29660539/863584b1-0396-4784-bcc7-d980b267c7fb)

2. I noticed that the training data mentioned in the paper has been made public in the GitHub repo, but I couldn’t find it in yours. Is it under preparation?

![20230613145137](https://github.com/WeOpenML/PandaLM/assets/29660539/0662cf12-5efb-492b-bc6e-6af97c7908ae)

**Comment by qianlanwyd** [comment]
1. Currently we don't have analysis about it. Maybe we will add some in the future work.
2. Yes, we will upload more resources including training data soon.

**Comment by qianlanwyd** [comment]
Data uploaded.
