### ISSUE TITLE
Training PandaLM for other abstract metrics

### ISSUE THREAD

**Issue by ogencoglu** [WeOpenML/PandaLM#2]
Thanks for the great work!

If I understood correctly, PandaLM evaluates the model responses with respect to correctness (if there is an objective ground truth) and humanness because it was trained on that sort of human annotations. 

Can this framework be used to compare responses with respect to other abstract metrics such as "creativity" or "formalness" or "conciseness" etc. if such training data is collected?

**Comment by zhuohaoyu** [comment]
Hi, this framework can be applied to evaluate other metrics. However, these abstract metrics can be more subjective to evaluate and thus harder to collect high quality data to train and evaluate. We do have plans to evaluate from more perspectives, please stay tuned for our upcoming paper.
