### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by AIRobotZhang** [WeOpenML/PandaLM#21]
Hello, Table 1-2 is not consistent with results reported in [https://github.com/WeOpenML/PandaLM/tree/main#test-data](https://github.com/WeOpenML/PandaLM/tree/main#test-data)

**Comment by zhuohaoyu** [comment]
Hi, we are aware of the issue and it was fixed in https://github.com/WeOpenML/PandaLM/pull/22. The results are different because we updated our inference methods with PandaLM/ChatGPT as reported in our paper to calculate more robust metrics. Please refer to our paper for latest results.

**Comment by AIRobotZhang** [comment]
> Hi, we are aware of the issue and it was fixed in #22. The results are different because we updated our inference methods with PandaLM/ChatGPT as reported in our paper to calculate more robust metrics. Please refer to our paper for latest results.

How calculate the F1 score in Table 2. Is F1 score micro or macro?

**Comment by arjunbansal** [comment]
> The results are different because we updated our inference methods with PandaLM/ChatGPT as reported in our paper to calculate more robust metrics. Please refer to our paper for latest results.

Do you plan to share the inference dataset files that accompany the updated methods?
