### ISSUE TITLE
论文提及到PandaLM是基于LlaMA做指令微调的，想问问作者微调数据和代码在哪个地方吗？

### ISSUE THREAD

**Issue by robotsp** [WeOpenML/PandaLM#24]
如题

@zhuohaoyu @qianlanwyd

**Comment by qianlanwyd** [comment]
看这个脚本，https://github.com/WeOpenML/PandaLM/blob/main/pandalm/scripts/inst-tune.sh

**Comment by robotsp** [comment]
微调数据 human reference有吗？ @qianlanwyd @zhuohaoyu
