### ISSUE TITLE
Command 'pip --disable-pip-version-check install -r requirements.txt' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Wendong-Fan** [WeOpenML/PandaLM#4]
when I run pip install -r requirements.txt, I got an error:

The conflict is caused by:
    The user requested torch
    accelerate 0.18.0 depends on torch>=1.4.0
    peft 0.2.0 depends on torch>=1.13.0
    torchaudio 2.0.0 depends on torch==2.0.0
    torchvision 0.15.0 depends on torch==2.0.0+cu117

**Comment by zhuohaoyu** [comment]
Try reinstalling PyTorch 2.0 on a clean environment: https://pytorch.org/get-started/locally/ or use our conda-env.yml.

**Comment by tytcc** [comment]
Installing tochvision=0.15.1 works for me.
