### ISSUE TITLE
Definition of 'Tie' in paper

### ISSUE THREAD

**Issue by Baiiiiiiiiii** [WeOpenML/PandaLM#41]
Hi,

Thank you for sharing this great work. I have a question about the description in PandaLM paper.

![image](https://github.com/WeOpenML/PandaLM/assets/94792611/1a640f52-9dc3-4c90-beb8-263fdb527ffc)

The paper said:
> The conflicting evaluation results are then modified to ‘Tie’.

What do conflicting evaluation results mean?

Does the following case also be modified as 'Tie'?
- the first eval result is '1', and then changing the order of input, we get the second eval result 'Tie'

Also, could you please share your code judging the conflicting results?

I appreciate your help.

**Comment by qianlanwyd** [comment]
If the results are both tie, the final result is tie
If the results are same (same means conflict because the reponses change positions), the final result is tie.
Otherwise, follow the first result.
