### ISSUE TITLE
排序的原因

### ISSUE THREAD

**Issue by guozhiyao** [WeOpenML/PandaLM#6]
你好，请问能否获得排序的reason？我测试了下，目前只能输出0/1/2，没有给出为什么这么排序。

**Comment by zhuohaoyu** [comment]
For case study, we recommend running gradio as provided in the doc and it shows everything PandaLM generates. For batch inferencing, we parsed the outputs of PandaLM to only integers for convenience to calculate metrics. If you want more outputs while running batch inference, feel free to print everything here(https://github.com/WeOpenML/PandaLM/blob/db9b314b5c72a1ef90574d011525a7caca3750df/pandalm/utils/evaluation_pipeline.py#L116).

**Comment by CRH400AF-A** [comment]
For "we parsed the outputs of PandaLM to only integers for convenience to calculate metrics.",
are you parsing the output into integers in the code below?

```python
def parse_pandalm_response(self, text):
      sp = text.strip().split("\n")
      if sp[0] in ["1", "2"]:
          return int(sp[0])
      elif sp[0].lower() == "tie":
          return 0
      else:
          return 0
```
